---
title: "Publications"
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = FALSE)
library(rmarkdown)
library(knitr)

```

[<font size="4">Pneumonia following symptomatic influenza infection among Nicaraguan children before and after introduction of the pneumococcal conjugate vaccine</font>](jid2020.html)  
<font size="2">**John Kubale**, Angel Balmaseda, Nery Sanchez, Roger Lopez, Lionel Gresh, Sergio Ojeda, Eva Harris, Guillermina Kuan, Jon Zelner, Aubree Gordon</font>


[<font size="4">Individual-Level Association of Influenza Infection with Subsequent  Pneumonia: A Case-Control And Prospective Cohort Study</font>](cidpneumo.html)  
<font size="2">**John Kubale**, Guillermina Kuan, Lionel Gresh, Sergio Ojeda, Amy Schiller, Nery Sanchez, Roger Lopez, Eduardo Azziz-Baumgartner, Steph Wraith, Eva Harris, Angel Balmaseda, Jon Zelner, Aubree Gordon</font>



[<font size="4">Assessing the Incidence of Symptomatic Respiratory Syncytial Virus Illness Within a Prospective Birth Cohort in Managua, Nicaragua</font>](cidrsv.html)  
<font size="2">**John Kubale**, Guillermina Kuan, Lionel Gresh, Sergio Ojeda, Eduardo Azziz-Baumgartner, Nery Sanchez, Roger Lopez, Eva Harris, Angel Balmaseda, Aubree Gordon</font>



[<font size="4">Simulation models predict that school-age children are responsible for most  human-to-mosquito Plasmodium falciparum transmission in southern Malawi</font>](https://pubmed.ncbi.nlm.nih.gov/29615044/)    
<font size="2">Jenna E Coalson, Lauren M Cohee, Andrea G Buchwald, Andrew Nyambalo, **John Kubale**, Karl B Seydel, Don Mathanga, Terrie E Taylor, Miriam K Laufer, Mark L Wilson</font>

  
[<font size="4">Analyses of infectious disease patterns and drivers largely lack insights from social epidemiology: contemporary patterns and future opportunities</font>](https://pubmed.ncbi.nlm.nih.gov/27799618/)    
<font size="2">Grace A Noppert, **John T Kubale**, Mark L Wilson</font> 



